import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import BackButton from '../components/common/BackButton.jsx';
import styles from './Onboarding.module.css';
import { onboardingSteps, TOTAL_ONBOARDING_STEPS } from '../data/onboardingSteps.js';

// Shared illustration collage (same visual language as the Login/Signup
// split-screen pages — no real photos rendered, just placeholder shapes).
function FlipgridVisual() {
  return (
    <div className={`${styles.visual} ${styles.visualFixed}`}>
      <div className={styles.bubbleIcon} aria-hidden="true">
        💬
      </div>
      <div className={styles.grid}>
        <div className={styles.gridControls} aria-hidden="true" />
        <div className={styles.gridTiles}>
          {Array.from({ length: 9 }).map((_, i) => (
            <div className={styles.tile} key={i} />
          ))}
        </div>
        <div className={styles.gridPlayer} aria-hidden="true" />
        <div className={styles.gridFooter} aria-hidden="true" />
      </div>
      <div className={styles.flowerIcon} aria-hidden="true" />
      <div className={styles.replyCardBehind} aria-hidden="true">
        <span className={styles.avatarBadge}>Lana</span>
      </div>
      <div className={styles.replyCard}>
        <div className={styles.replyPhoto} />
        <div className={styles.replyLine} />
        <div className={`${styles.replyLine} ${styles.replyLineShort}`} />
        <div className={styles.replyAvatar} />
      </div>
    </div>
  );
}

// Step 2 — a settings-panel mockup (question prompt, feedback mode, reply
// length, toggles) with a recording-in-progress frame overlapping it. The
// frame's "camera preview" is a gradient placeholder, not a real photo.
function RecordQuestionVisual() {
  return (
    <div className={`${styles.visual} ${styles.recordVisual}`}>
      <div className={styles.settingsPanel} aria-hidden="true">
        <p className={styles.settingsLabel}>What&apos;s your question about?</p>
        <div className={styles.settingsInput}>
          <span className={styles.settingsPlaceholder}>Book review and recommendation</span>
          <span className={styles.settingsCounter}>/50</span>
        </div>

        <p className={styles.settingsLabel}>Give the students instant, personalized feedback?</p>
        <div className={styles.optionRow}>
          <div className={`${styles.optionCard} ${styles.optionCardActive}`}>
            <span className={styles.optionIcon} />
            <span className={styles.optionTitle}>Yes - Graded</span>
            <span className={styles.optionSubtitle}>
              Students receive a score/grade, a rubric you provide, or one generated by Coraltalk
            </span>
          </div>
          <div className={styles.optionCard}>
            <span className={styles.optionIcon} />
          </div>
        </div>

        <p className={styles.settingsLabel}>Maximum video reply length</p>
        <div className={styles.settingsInput}>
          <span>90 seconds</span>
        </div>

        <p className={styles.settingsLabel}>Allow students to reply via</p>
        <div className={styles.toggleRow}>
          <span>Enable transcript view</span>
          <span className={`${styles.toggle} ${styles.toggleOn}`} />
        </div>
        <div className={styles.toggleRow}>
          <span>Enable AI summaries</span>
          <span className={styles.toggle} />
        </div>
        <div className={styles.toggleRow}>
          <span>Hide video replies until I approve</span>
          <span className={`${styles.toggle} ${styles.toggleOn}`} />
        </div>
      </div>

      <div className={styles.recordFrame} aria-hidden="true">
        <div className={styles.recordPreview} />
        <span className={styles.recordDot} />
        <span className={styles.flipIcon} />
      </div>
    </div>
  );
}

// Step 3 — a "Visible/Hidden" dropdown expanded above a video-reply card
// (gradient placeholder image, not a real photo) with its caption.
function ApproveRepliesVisual() {
  return (
    <div className={styles.visual}>
      <div className={styles.replyStack}>
        <div className={styles.dropdownPill}>
          Visible <span className={styles.chevron}>⌄</span>
        </div>
        <div className={styles.dropdownList}>
          <div className={styles.dropdownRow}>
            <span className={`${styles.statusDot} ${styles.statusDotTeal}`} />
            Visible
          </div>
          <div className={styles.dropdownRow}>
            <span className={`${styles.statusDot} ${styles.statusDotPink}`} />
            Hidden
          </div>
        </div>
        <div className={styles.thumbCard}>
          <span className={styles.thumbLabel}>Aristedes</span>
        </div>
        <div className={styles.captionBubble}>My favourite part in the novel was when Jim[...]</div>
      </div>
    </div>
  );
}

// Step 4 — the same video-grid collage as step 1, but standalone: a
// gradient-ringed avatar overlapping the corner instead of a floating reply
// card, and no chat-bubble icon.
function DiscussionsVisual() {
  return (
    <div className={`${styles.visual} ${styles.visualFixed}`}>
      <div className={styles.grid}>
        <div className={styles.gridControls} aria-hidden="true" />
        <div className={styles.gridTiles}>
          {Array.from({ length: 9 }).map((_, i) => (
            <div className={styles.tile} key={i} />
          ))}
        </div>
        <div className={styles.gridPlayer} aria-hidden="true" />
        <div className={styles.gridFooter} aria-hidden="true" />
      </div>
      <div className={styles.flowerIcon} aria-hidden="true" />
      <div className={styles.standaloneAvatar} aria-hidden="true" />
    </div>
  );
}

// Step 5 — an email-invite compose mockup. Every field is a real, controlled
// input now — From, To, Subject, and the message body (labeled "Subject"
// twice in the reference design; the parent still tracks them as separate
// values internally) — so the whole compose form is actually editable, not
// just the "To" field.
function ShareInviteVisual({
  fromValue,
  onFromChange,
  toValue,
  onToChange,
  subjectValue,
  onSubjectChange,
  messageValue,
  onMessageChange,
}) {
  return (
    <div className={styles.visual}>
      <div className={styles.emailForm}>
        <div className={styles.emailField}>
          <p className={styles.emailLabel}>From</p>
          <div className={styles.emailBox}>
            <input
              type="text"
              className={styles.emailToInput}
              value={fromValue}
              onChange={(event) => onFromChange(event.target.value)}
              aria-label="From"
            />
          </div>
        </div>
        <div className={styles.emailField}>
          <p className={styles.emailLabel}>To</p>
          <div className={styles.emailBox}>
            <input
              type="text"
              className={`${styles.emailToInput} ${styles.emailToInputWithAddBtn}`}
              placeholder="Add email(s)"
              value={toValue}
              onChange={(event) => onToChange(event.target.value)}
              aria-label="Invite email addresses"
            />
            <span className={styles.addBtn} aria-hidden="true">
              +
            </span>
          </div>
        </div>
        <div className={styles.emailField}>
          <p className={styles.emailLabel}>Subject</p>
          <div className={styles.emailBox}>
            <input
              type="text"
              className={styles.emailToInput}
              value={subjectValue}
              onChange={(event) => onSubjectChange(event.target.value)}
              aria-label="Subject"
            />
          </div>
        </div>
        <div className={styles.emailField}>
          <p className={styles.emailLabel}>Subject</p>
          <div className={`${styles.emailBox} ${styles.emailTextarea}`}>
            <textarea
              className={styles.emailMessageInput}
              value={messageValue}
              onChange={(event) => onMessageChange(event.target.value)}
              aria-label="Message"
              rows={4}
            />
          </div>
        </div>
      </div>
    </div>
  );
}

// Maps each step's `id` (see src/data/onboardingSteps.js) to its
// illustration. Add the next step's visual here as its reference design
// arrives — nothing else about the flow needs to change.
const STEP_VISUALS = {
  'missed-flipgrid': FlipgridVisual,
  'record-question': RecordQuestionVisual,
  'approve-replies': ApproveRepliesVisual,
  'watch-discussions': DiscussionsVisual,
  'share-invites': ShareInviteVisual,
};

const DEFAULT_INVITE_FROM = 'Melissa Morgan via VidTickets <share@coraltalk.com>';
const DEFAULT_INVITE_SUBJECT = 'An awesome Flipgrid replacement you may like';
const DEFAULT_INVITE_MESSAGE =
  "I found this new tool that replaces Flipgrid. Thought I'd share it with you.\n\n" +
  'This invite will get you access. Enjoy!\n' +
  'https://www.vidtickets.coraltalk.com';

function Onboarding() {
  const [currentStep, setCurrentStep] = useState(0);
  const [inviteFrom, setInviteFrom] = useState(DEFAULT_INVITE_FROM);
  const [inviteEmails, setInviteEmails] = useState('');
  const [inviteSubject, setInviteSubject] = useState(DEFAULT_INVITE_SUBJECT);
  const [inviteMessage, setInviteMessage] = useState(DEFAULT_INVITE_MESSAGE);
  const [invitesSent, setInvitesSent] = useState(false);
  const step = onboardingSteps[currentStep];
  const Visual = step ? STEP_VISUALS[step.id] : null;
  const navigate = useNavigate();
  const isInviteStepFilled = inviteEmails.trim().length > 0;

  const handleContinue = () => {
    if (currentStep + 1 < onboardingSteps.length) {
      setCurrentStep((prev) => prev + 1);
    } else {
      // Demo only — remaining steps of the "How VidTickets Work" flow will
      // be added here as their reference designs come in.
      window.alert('More onboarding steps coming soon (demo)');
    }
  };

  const handleSendInvites = () => {
    if (!isInviteStepFilled) {
      // Nothing entered — same as Skip, just head to the dashboard.
      navigate('/app');
      return;
    }
    // Demo only — wire this up to your invite-sending backend. Show the
    // button's "Sent" confirmation briefly before moving on.
    setInvitesSent(true);
    window.setTimeout(() => navigate('/app'), 700);
  };

  const handleSkip = () => {
    navigate('/app');
  };

  const handleBack = () => {
    if (currentStep === 0) {
      navigate('/signup/teacher');
    } else {
      setCurrentStep((prev) => prev - 1);
    }
  };

  const renderBody = () => {
    if (!step.bodyBoldPhrase) return step.body;
    const parts = step.body.split(step.bodyBoldPhrase);
    return (
      <>
        {parts[0]}
        <strong>{step.bodyBoldPhrase}</strong>
        {parts[1]}
      </>
    );
  };

  return (
    <div className={styles.shell}>
      <div className={styles.dot} aria-hidden="true" />
      <div className={styles.ringTop} aria-hidden="true" />
      <div className={styles.sphereTop} aria-hidden="true" />
      <div className={styles.sphereBottom} aria-hidden="true" />
      <div className={styles.ringBottom} aria-hidden="true" />

      <div className={styles.brandMark}>
        VidTickets<sup>7</sup>
      </div>

      {step && (
        <div className={styles.card}>
          <div className={styles.backSlot}>
            <BackButton onClick={handleBack} />
          </div>

          <div className={styles.content}>
            <div className={styles.text}>
              <p className={styles.eyebrow}>
                {currentStep + 1} of {TOTAL_ONBOARDING_STEPS} | {step.category}
              </p>
              <h1 className={styles.headline}>
                {step.headlineLines.map((line, i) => {
                  const isAccentLine = i === step.accentLineIndex;
                  if (isAccentLine) {
                    return (
                      <span key={line} className={styles.accent}>
                        {line}
                      </span>
                    );
                  }
                  // Optionally highlight a trailing period, e.g. "You missed Flipgrid."
                  const highlightPeriod = step.highlightTrailingPeriod && i === step.accentLineIndex - 1;
                  const endsWithPeriod = highlightPeriod && line.endsWith('.');
                  const body = endsWithPeriod ? line.slice(0, -1) : line;
                  const isLastLine = i === step.headlineLines.length - 1;
                  return (
                    <span key={line}>
                      {body}
                      {endsWithPeriod && <span className={styles.accent}>.</span>}
                      {!isLastLine && <br />}
                    </span>
                  );
                })}
              </h1>
              <p className={styles.body}>{renderBody()}</p>
            </div>

            {Visual &&
              (step.id === 'share-invites' ? (
                <Visual
                  fromValue={inviteFrom}
                  onFromChange={setInviteFrom}
                  toValue={inviteEmails}
                  onToChange={setInviteEmails}
                  subjectValue={inviteSubject}
                  onSubjectChange={setInviteSubject}
                  messageValue={inviteMessage}
                  onMessageChange={setInviteMessage}
                />
              ) : (
                <Visual />
              ))}
          </div>

          <div className={styles.divider} />

          {step.isFinalStep ? (
            <div className={`${styles.actions} ${styles.actionsBetween}`}>
              <button type="button" className={styles.skipLink} onClick={handleSkip} disabled={invitesSent}>
                Skip
              </button>
              <button
                type="button"
                className={`${styles.sendBtn} ${invitesSent ? styles.sendBtnSent : ''}`}
                onClick={handleSendInvites}
                disabled={invitesSent}
              >
                {invitesSent ? 'Sent ✓' : 'Send Invites →'}
              </button>
            </div>
          ) : (
            <div className={styles.actions}>
              <button type="button" className={styles.continueBtn} onClick={handleContinue}>
                Continue
              </button>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

export default Onboarding;
