import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import AppSidebar from '../components/app/AppSidebar.jsx';
import styles from './VidTicketNew.module.css';

const QUESTION_MAX = 50;
const REPLY_LENGTH_MIN = 15;
const REPLY_LENGTH_MAX = 300; // 5 minutes
const REPLY_LENGTH_STEP = 15;

function formatDuration(totalSeconds) {
  const minutes = Math.floor(totalSeconds / 60);
  const seconds = totalSeconds % 60;
  return `${minutes}:${String(seconds).padStart(2, '0')}`;
}

function Toggle({ checked, onChange, label }) {
  return (
    <button
      type="button"
      role="switch"
      aria-checked={checked}
      aria-label={label}
      className={`${styles.toggle} ${checked ? styles.toggleOn : ''}`}
      onClick={() => onChange(!checked)}
    />
  );
}

// The "create a Vid Ticket" flow's first step — question prompt, feedback
// mode, reply length, and reply settings. Reached from the Dashboard's
// "+ New Vid Ticket" button.
function VidTicketNew() {
  const navigate = useNavigate();
  const [question, setQuestion] = useState('');
  const [feedbackMode, setFeedbackMode] = useState('participation');
  const [replySeconds, setReplySeconds] = useState(90);
  const [allowReplies, setAllowReplies] = useState(true);
  const [transcriptView, setTranscriptView] = useState(false);
  const [aiSummaries, setAiSummaries] = useState(false);
  const [hideUntilApproved, setHideUntilApproved] = useState(true);

  const adjustReplyLength = (delta) => {
    setReplySeconds((prev) => Math.min(REPLY_LENGTH_MAX, Math.max(REPLY_LENGTH_MIN, prev + delta)));
  };

  const handleRecord = () => {
    // Carries the max reply length picked above into the recording page as
    // route state, so its countdown/auto-stop timer matches what was set
    // here instead of a hardcoded default.
    navigate('/app/new-ticket/record', { state: { maxSeconds: replySeconds } });
  };

  return (
    <div className={styles.shell}>
      <div className={styles.frame}>
        <AppSidebar variant="ticket" />

        <main className={styles.main}>
          <div className={styles.header}>
            <button
              type="button"
              className={styles.backCircle}
              aria-label="Back to Dashboard"
              onClick={() => navigate('/app')}
            >
              ←
            </button>
            <h1 className={styles.pageTitle}>Vid Ticket</h1>
          </div>

          <div className={styles.progressBar} aria-hidden="true">
            <span className={`${styles.progressSegment} ${styles.progressActive}`} />
            <span className={styles.progressSegment} />
            <span className={styles.progressSegment} />
          </div>

          <div className={styles.formCard}>
            <div className={styles.field}>
              <p className={styles.fieldLabel}>What&apos;s your question about?</p>
              <div className={styles.inputRow}>
                <input
                  type="text"
                  className={styles.textInput}
                  placeholder="Book review and recommendation"
                  value={question}
                  maxLength={QUESTION_MAX}
                  onChange={(event) => setQuestion(event.target.value)}
                  aria-label="What's your question about?"
                />
                <span className={styles.counter}>
                  {question.length}/{QUESTION_MAX}
                </span>
              </div>
            </div>

            <div className={styles.field}>
              <p className={styles.fieldLabel}>Give the students instant, personalized feedback?</p>
              <div className={styles.feedbackOptions}>
                <button
                  type="button"
                  className={`${styles.optionCard} ${feedbackMode === 'graded' ? styles.optionCardActive : ''}`}
                  onClick={() => setFeedbackMode('graded')}
                >
                  <span className={styles.optionIcon} aria-hidden="true">
                    📊
                  </span>
                  <span className={styles.optionTitle}>
                    <span className={styles.lockIcon} aria-hidden="true">
                      🔒
                    </span>
                    Yes - Graded
                  </span>
                  <p className={styles.optionSubtitle}>
                    Students receive a score based on either a rubric you provide or one automatically generated by
                    Coral.
                  </p>
                </button>
                <button
                  type="button"
                  className={`${styles.optionCard} ${feedbackMode === 'participation' ? styles.optionCardActive : ''}`}
                  onClick={() => setFeedbackMode('participation')}
                >
                  <span className={styles.optionIcon} aria-hidden="true">
                    {feedbackMode === 'participation' ? '✅' : '⬜'}
                  </span>
                  <span className={styles.optionTitle}>No - Participation only</span>
                  <p className={styles.optionSubtitle}>
                    Students do not receive feedback or a grade. You can still leave replies.
                  </p>
                </button>
              </div>
            </div>

            <div className={styles.field}>
              <p className={styles.fieldLabel}>
                Maximum video reply length: <span className={styles.fieldHint}>up to 5 minutes</span>
              </p>
              <div className={styles.stepperRow}>
                <button
                  type="button"
                  className={styles.stepperBtn}
                  onClick={() => adjustReplyLength(-REPLY_LENGTH_STEP)}
                  disabled={replySeconds <= REPLY_LENGTH_MIN}
                  aria-label="Decrease reply length"
                >
                  −
                </button>
                <span className={styles.stepperValue}>{formatDuration(replySeconds)}</span>
                <button
                  type="button"
                  className={styles.stepperBtn}
                  onClick={() => adjustReplyLength(REPLY_LENGTH_STEP)}
                  disabled={replySeconds >= REPLY_LENGTH_MAX}
                  aria-label="Increase reply length"
                >
                  +
                </button>
              </div>
            </div>

            <div className={styles.toggleField}>
              <span>Allow students to reply via video to other students?</span>
              <Toggle
                checked={allowReplies}
                onChange={setAllowReplies}
                label="Allow students to reply via video to other students"
              />
            </div>
            <div className={styles.toggleField}>
              <span>Enable transcript view</span>
              <Toggle checked={transcriptView} onChange={setTranscriptView} label="Enable transcript view" />
            </div>
            <div className={styles.toggleField}>
              <span>Enable AI summaries</span>
              <Toggle checked={aiSummaries} onChange={setAiSummaries} label="Enable AI summaries" />
            </div>
            <div className={styles.toggleField}>
              <span>Hide video replies until I approve them</span>
              <Toggle
                checked={hideUntilApproved}
                onChange={setHideUntilApproved}
                label="Hide video replies until I approve them"
              />
            </div>
          </div>

          <div className={styles.actions}>
            <button type="button" className={styles.recordBtn} onClick={handleRecord}>
              Record your question →
            </button>
          </div>
        </main>
      </div>
    </div>
  );
}

export default VidTicketNew;
